name: 'Test'

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      saves_changed: ${{ steps.reading_save_file.outputs.saves_changed }}
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: API caching
        uses: ./
      - name: Read and print save file
        id: reading_save_file
        run: |
          contents=$( cat output.txt )
          echo "$contents"
          same=$( cat same.txt )
          changed=[ "$same" = "1" ]
          echo "::set-output name=saves_changed::$changed"
          echo "$changed"
          echo "${{ steps.reading_save_file.outputs.saves_changed }}"
      - name: Commit save data
        if: steps.reading_save_file.outputs.saves_changed
        run: |
          echo "Hello"
          echo "${{ steps.reading_save_file.outputs.saves_changed }}"
