name: 'Test'

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3
      - name: API caching
        uses: ./
      - name: Remove temporary file
        run: |
          rm changed.txt
      - name: Pull data
        run: git pull
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Overwritten by Github Actions - ${date}'
