name: 'Test'

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      save_contents: ${{ steps.reading_save_file.outputs.contents }}
      saves_changed: ${{ steps.reading_save_file.outputs.saves_changed }}
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: API caching
        uses: ./
      - name: Read and print save file
        id: reading_save_file
        run: |
          contents=$( cat output.txt )
          changed=$( cat changed.txt )
          echo "::set-output name=saves_changed::$changed"
          echo "::set-output name=save_contents::$contents"
      - name: Commit save data
        if: ${{ steps.reading_save_file.outputs.saves_changed == 'true' }}
        run: |
          echo "Hello"
          echo "${{ steps.reading_save_file.outputs.saves_changed }}"
          echo "${{ steps.reading_save_file.outputs.contents }}"
