name: 'Test'

on:
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: API caching
        uses: ./
      - name: Print save file
        run: |
          contents=$( cat output.txt )
          echo "$contents"
      - name: Commit save data
        if: ${{ '1' == '1' }}
        run: |
          echo "Hello"
